version: '3.8'
services:
  tp-foyer:
    image: ranim1707/tp-foyer:5.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ranim
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
    ports:

      - "3306:3306"

      - "3309:3306"

