
# DB Configuration :
spring.datasource.url=jdbc:mysql://localhost:3306/db?ranim
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
=======
spring.jpa.open-in-view=false
>>>>>>> 33e6ff03de4c4771dc3fb994ee2ef5a2731ff557

# Web Server (Tomcat) configuration :
server.port=8089
server.servlet.context-path=/tpfoyer
