
# DB Configuration :
spring.datasource.url=jdbc:mysqldb://localhost:3306/db?ranim
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.jpa.open-in-view=false

# Web Server (Tomcat) configuration :
server.port=8089
server.servlet.context-path=/tpfoyer
