
# DB Configuration :
spring.datasource.url=jdbc:mysql://mysqldb:3309/ranim
spring.datasource.username=root
spring.datasource.password=
# Configuration de Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect  # ou org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Web Server (Tomcat) configuration :
server.port=8089
server.servlet.context-path=/tpfoyer
